/**
 * Structured spec interface generated by Claude from user prompts.
 * This is the contract between the LLM and the code generator.
 */
export interface AppSpec {
  appName: string;
  description: string;
  type: 'frontend-only' | 'fullstack';

  pages: PageSpec[];
  dataModels: DataModelSpec[];
  apiEndpoints: ApiEndpointSpec[];

  features: string[];
  needsDatabase: boolean;
}

export interface PageSpec {
  name: string;
  path: string;
  description: string;
  components: string[];
}

export interface DataModelSpec {
  name: string;
  fields: FieldSpec[];
}

export interface FieldSpec {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'date' | 'enum';
  required: boolean;
  enumValues?: string[];
  defaultValue?: string;
}

export interface ApiEndpointSpec {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  description: string;
  requestBody?: Record<string, string>;
  responseType?: string;
}

export interface IterationDiff {
  addedPages: PageSpec[];
  modifiedPages: { name: string; changes: string }[];
  removedPages: string[];
  addedModels: DataModelSpec[];
  modifiedModels: { name: string; changes: string }[];
  addedEndpoints: ApiEndpointSpec[];
  addedFeatures: string[];
  updatedSpec: AppSpec;
}
